"use client";

import { useState } from "react";
import QRCode from "qrcode";
import jsPDF from "jspdf";

export default function Home() {
  const [form, setForm] = useState({
    name: "",
    department: "",
    rollNo: "",
    phoneNumber: "",
    email: "",
  });
  const [ticket, setTicket] = useState<any>(null);
  const [qrCode, setQrCode] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (loading) return; // prevent double submit

    setLoading(true);

    try {
      // 🔹 Change this URL to your actual backend endpoint
      const res = await fetch("https://carrent-1a5af1afc087.herokuapp.com/tickets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });

      const data = await res.json();

      if (!res.ok) {
        alert(data.error || "Error creating student record");
        return;
      }

      // 🔹 Generate QR code (locally)
      const qr = await QRCode.toDataURL(`rollNo: ${data.rollNo}`);

      setTicket(data);
      setQrCode(qr);
    } catch (error) {
      console.error(error);
      alert("Failed to submit data");
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!ticket) return;
    const doc = new jsPDF();
    // Header
    doc.setFillColor(59, 130, 246); // blue-500
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Student Ticket", 105, 18, { align: "center" });
    doc.setTextColor(33, 37, 41); // dark text
    doc.setFontSize(14);
    // Ticket box
    doc.setDrawColor(59, 130, 246);
    doc.roundedRect(15, 40, 180, 90, 6, 6);
    doc.text(`Name:`, 25, 55);
    doc.text(ticket.name, 60, 55);
    doc.text(`Department:`, 25, 65);
    doc.text(ticket.department, 60, 65);
    doc.text(`Roll No:`, 25, 75);
    doc.text(ticket.rollNo, 60, 75);
    doc.text(`Phone Number:`, 25, 85);
    doc.text(ticket.phoneNumber, 60, 85);
    doc.text(`Email:`, 25, 95);
    doc.text(ticket.email, 60, 95);
    // QR code
    if (qrCode) {
      doc.text("QR Code:", 140, 60);
      doc.addImage(qrCode, "PNG", 140, 65, 45, 45);
    }
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text("Generated by TicketApp", 105, 140, { align: "center" });
    doc.save("student-ticket.pdf");
  };

  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-blue-100 via-indigo-100 to-purple-100 p-6">
      <h1 className="mb-8 text-4xl font-extrabold text-center tracking-tight text-black drop-shadow-lg">
        TICKET GENERATION FORM
      </h1>
      {!ticket ? (
        <form
          onSubmit={handleSubmit}
          className="bg-white p-6 rounded-2xl shadow-md w-full max-w-md space-y-4"
        >
          <h2 className="text-2xl font-bold text-center">
            🎟️ Student Ticket Form
          </h2>

          <input
            type="text"
            name="name"
            placeholder="Student Name"
            value={form.name}
            onChange={handleChange}
            className="form-input"
            required
          />

          <input
            type="text"
            name="department"
            placeholder="department"
            value={form.department}
            onChange={handleChange}
            className="form-input"
            required
          />

          <input
            type="text"
            name="rollNo"
            placeholder="rollNo"
            value={form.rollNo}
            onChange={handleChange}
            className="form-input"
            required
          />
          <input
            type="text"
            name="phoneNumber"
            placeholder="Phone Number"
            value={form.phoneNumber}
            onChange={handleChange}
            className="form-input"
            required
          />
          <input
            type="text"
            name="email"
            placeholder="email"
            value={form.email}
            onChange={handleChange}
            className="form-input"
            required
          />

          <button
            type="submit"
            disabled={loading}
            aria-busy={loading}
            className={`w-full bg-blue-500 text-white py-2 rounded hover:bg-blue-600 flex items-center justify-center ${
              loading ? "opacity-60 cursor-not-allowed" : ""
            }`}
          >
            {loading ? (
              <>
                <span className="spinner mr-2" aria-hidden></span>
                Submitting...
              </>
            ) : (
              "Submit & Generate Ticket"
            )}
          </button>
        </form>
      ) : (
        <div className="bg-white p-6 rounded-2xl shadow-md w-full max-w-md space-y-3 text-center mx-auto flex flex-col items-center">
          <h2 className="text-xl font-bold">🎫 Student Ticket</h2>
          <p>
            <strong>Name:</strong> {ticket.name}
          </p>
          <p>
            <strong>department:</strong> {ticket.department}
          </p>
          <p>
            <strong>rollNo:</strong> {ticket.rollNo}
          </p>
          <p>
            <strong>phoneNumber:</strong> {ticket.phoneNumber}
          </p>
          <p>
            <strong>email:</strong> {ticket.email}
          </p>

          {qrCode && (
            <img
              src={qrCode}
              alt="QR Code"
              className="mx-auto mt-4 w-40 h-40 object-contain border border-blue-200 rounded-lg bg-gray-50"
            />
          )}

          <button
            onClick={handleDownloadPDF}
            className="mt-4 px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600"
          >
            Download Ticket as PDF
          </button>

          <button
            onClick={() => {
              setTicket(null);
              setQrCode("");
              setForm({
                name: "",
                department: "",
                rollNo: "",
                phoneNumber: "",
                email: "",
              });
            }}
            className="mt-2 px-4 py-2 bg-gray-300 rounded hover:bg-gray-400"
          >
            Create Another Ticket
          </button>
        </div>
      )}
    </main>
  );
}
